import Footer from "components/Footer";
import Header from "components/Header";
import { type NextPage } from "next";
import { GetServerSideProps } from 'next';
import Head from "next/head";
import Link from "next/link";

const courses = () => {
    return (
        <>
        <Head>
          <title>CHULA MOOC</title>
          <meta name="description" content="Generated by create-mooc-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <div className="">
        <center className="box-border ">
          <h3 className="mt-5 mb-3 box-border text-3xl font-extralight text-inherit leading-[1.2] ">
            รายวิชาในหลักสูตร
          </h3>
          <hr className="my-6 box-content h-0 overflow-visible border-solid border-transparent/10 border-[1px_0px_0px]" />
        </center>
        <div className="mx-20 ">
          <div className="box-border overflow-y-scroll h-[600px] ">
            <div className="box-border justify-center lg:columns-3 columns-1 md:columns-2 space-y-3 ">
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW011101_กฎหมายกับสังคม"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW011201_หลักกฎหมายเอกชน"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW012102_นิติปรัชญา"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW012204 กฎหมายว่าด้วยหนี้"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW012205_กฎหมายว่าด้วยละเมิดฯ"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW012206_เอกเทศสัญญา_1"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW012401_หลักกฎหมายมหาชน"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW012501 กฎหมายอาญา : บทบัญญัติทั่วไป"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW013108 ภาษาอังกฤษสำหรับนักศึกษากฎหมาย 1"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW013208_การเจรจาต่อรองและสัญญาทางธุรกิจ"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW013209_กฎหมายว่าด้วยองค์กรทางธุรกิจ"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW013210_กฎหมายว่าด้วยครอบครัวและมรดก"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW013211_กฎหมายวิธีพิจารณาความแพ่ง_1"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW013213 กฎหมายวิธีพิจารณาความอาญา"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW013304 กฎหมายบริหารรัฐกิจและกิจการสาธารณะ"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW013401 กฎหมายระหว่างประเทศแผนกคดีบุคคล"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW013402 กฎหมายระหว่างประเทศแผนกคดีเมือง"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW013404 กฎหมายการค้าระหว่างประเทศและอนุญาโตตุลาการ"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW013505 กฎหมายที่ดินและการพัฒนาเมือง"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW014217 กฎหมายกับการสร้างธุรกิจดิจิทัล"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW014220_กฎหมายล้มละลายและฟื้นฟูกิจการ"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW014303_กฎหมายปกครอง"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW014409 กฎหมายมนุษยธรรมระหว่างประเทศ"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW014508_กฎหมายป้องกันและปราบปรามการทุจริต"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW014511_กฎหมายคุ้มครองข้อมูลส่วนบุคคล"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW014605_กฎหมายแรงงานและสวัสดิการสังคม"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW014606_กฎหมายภาษีอากร"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW014607 กฎหมายว่าด้วยการกระทำความผิดของเด็กและเยาวชน"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW_428312 กฎหมายระหว่างประเทศในเอเชียตะวันออกเฉียงใต้"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW_777100 ความรู้เบื้องต้นเกี่ยวกับกฎหมายทั่วไป"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW_777301 กฎหมายวิธีพิจารณาความอาญา สำหรับนักศึกษารัฐประศาสนศาสตร์"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW_777401 ทฤษฎีกฎหมายมหาชนและหลักการปกครองท้องถิ่น"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW_777440 กฎหมายภาษีอากร"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/LW_CL403559 การภาษีอากร"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/M_โครงการเสริมทักษะวิชาการ การเขียน-ตอบ ข้อสอบกฎหมาย สำหรับนักศึกษาชั้นปีที่ 1"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW011202_กฎหมายว่าด้วยนิติกรรมและสัญญา"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW011203_กฎหมายว่าด้วยทรัพย์สิน"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW012207_เอกเทศสัญญา 2"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW012208_กฎหมายว่าด้วยตั๋วเงินและประกันภัย"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW012302_กฎหมายรัฐธรรมนูญและสถาบันการเมือง"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW012502 กฎหมายอาญา : ภาคความผิด"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW012601_กฎหมายสิทธิมนุษยชน"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW012602_นโยบายและการบริหารงานยุติธรรม"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW013210_กฎหมายการแข่งขันการค้า"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW013211_กฎหมายธุรกิจ (ภาษาอังกฤษ)"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW013212_กฎหมายวิธีพิจารณาความแพ่ง_2"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW013214 กฎหมายว่าด้วยพยานหลักฐาน"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW013215_พระธรรมนูญศาลยุติธรรม"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW013217_กฎหมายทรัพย์สินทางปัญญา"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW013303 กฎหมายมหาชนทางเศรษฐกิจ"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW013404_กฎหมายว่าด้วยการส่งเสริมการลงทุนในประชาคมอาเซียน"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW013503_นิติวิทยาศาสตร์"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW013603_กฎหมายเศรษฐกิจระหว่างประเทศ"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW013604_กฎหมายสิ่งแวดล้อมและทรัพยากรธรรมชาติ"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW013605 อาชญวิทยา"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW013608_กฎหมายธุรกิจสถาบันการเงิน"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW014103_นิติทัศนะและจริยธรรมของนักกฎหมาย"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW014112_การระงับและการไกล่เกลี่ยข้อพิพาท"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW014149_ระเบียบวิธีวิจัยทางกฎหมาย"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW014506_การว่าความและศาลจำลอง"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW014507_กฎหมายว่าด้วยการกระทำความผิดของเด็กและเยาวชน"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW_ 777 100 ความรู้เบื้องต้นเกี่ยวกับกฎหมายทั่วไป"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW_ 777 302 กฎหมายว่าด้วยพยานหลักฐาน วปท."
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW_777 201 ทฤษฎีและความรับผิดชอบทางกฎหมายอาญา"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW_777 440 กฎหมายภาษีอากร 1 KKBS"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW_BS951111กฎหมายธรุกิจ(คณะบริหารธรุกิจฯ)"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/_LW_CL403742_กฎหมายธุรกิจ วปท."
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/__LW014761_สัมมนาวิชาชีพนักกฎหมาย"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/__LW014762_สัมมนากฎหมายธุรกิจ"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/___LW012204 กฎหมายว่าด้วยหนี้"
                />
              </div>
              <div className="box-border ">
                <img
                  className="box-border rounded border-none align-middle "
                  onmouseover="this.style.cursor='pointer'"
                  height="180px"
                  src="https://lawlibrarykku.online/getclassimg/___LW012501 กฎหมายอาญา : บทบัญญัติทั่วไป"
                />
              </div>
            </div>
          </div>
        </div>
        <hr className="my-6 box-content h-0 overflow-visible border-solid border-transparent/10 border-[1px_0px_0px]" />
      </div>
      <Footer />
    </>
    );
}

export default courses