import Footer from 'components/Footer';
import Header from 'components/Header';
import Head from "next/head";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
// import your icons
import { faCalendar, faBook, faPenToSquare, faFilePen, faBullseye, faThumbtack, faLaptop, faArrowLeft } from '@fortawesome/free-solid-svg-icons';
import Carousel from 'components/Carousel';

const Detail = () => {
    return (
        <>
        <Head>
            <title>Lawlibrarykku</title>
            <meta name="description" content="Generated by create-LawKKU-app" />
            <link rel="icon" href="/favicon.ico" />
            <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css" rel="stylesheet" />
        </Head>
        <Header />
        <div className="relative box-border ">
            <div className="w-full box-border bg-gradient-to-r from-cyan-100 to-blue-100 p-10 ">
            <div className="box-border ">
                <div className="box-border flex flex-wrap justify-center ">
                <div className="box-border w-full max-w-full flex-shrink-0 pr-5 md:w-5/6 lg:w-1/2 ">
                    <div className="box-border ">
                    <div className="box-border flex flex-wrap ">
                        <div className="box-border w-full max-w-full flex-shrink-0 ">
                        <h4 className="mt-0 mb-2 box-border text-2xl font-medium tracking-wide xl:text-2xl leading-[normal]  text-[rgba(17,17,17,1)]">
                            การดูแลตนเองเพื่อการเป็นผู้สูงวัยสุขภาพดีมีความสุข
                        </h4>
                        </div>
                    </div>
                    <div className="box-border flex flex-wrap ">
                        <div className="box-border w-full max-w-full flex-shrink-0 ">
                        <ul className="float-left mt-0 mb-6 box-border w-full pl-0 ">
                            <li className="float-left mb-0.5 box-border w-full text-base font-normal leading-7 tracking-normal text-[rgba(54,54,54,1)]">
                            <strong className="float-left box-border pr-3 font-semibold text-[rgba(37,37,37,1)]">
                                โดย :{" "}
                            </strong>
                            ทีมคณาจารย์จาก CHULA ARi
                            </li>
                            <li className="float-left mb-0.5 box-border w-full text-base font-normal leading-7 tracking-normal text-[rgba(54,54,54,1)]">
                            <strong className="float-left box-border pr-3 font-semibold text-[rgba(37,37,37,1)]">
                                รหัส :{" "}
                            </strong>
                            MOOC5021
                            </li>
                            <li className="float-left mb-0.5 box-border w-full text-base font-normal leading-7 tracking-normal text-[rgba(54,54,54,1)]">
                            <strong className="float-left box-border pr-3.5 font-semibold text-[rgba(37,37,37,1)]">
                                หมู่ :{" "}
                            </strong>
                            <div className="float-left mt-0.5 box-border rounded-2xl text-center text-xs font-medium leading-4 tracking-wide min-w-[55px] bg-[rgba(244,149,34,1)] text-white border-[rgba(244,149,34,1)]">
                                กฏหมาย
                            </div>
                            </li>
                        </ul>
                        </div>
                    </div>
                    <div className="box-border flex flex-wrap ">
                        <div className="box-border w-full max-w-full flex-shrink-0 pr-[calc(var(--bs-gutter-x)_/_2)] pl-[calc(var(--bs-gutter-x)_/_2)] mt-[var(--bs-gutter-y)]"></div>
                    </div>
                    <div className="box-border flex flex-wrap ">
                        <div className="box-border w-full max-w-full flex-shrink-0 ">
                        <h6 className="mt-0 mb-5 box-border text-lg font-semibold tracking-normal leading-[normal] font-[Sarabun,_sans-serif] text-[rgba(17,17,17,1)]">
                            ลงทะเบียนเรียน
                        </h6>
                        </div>
                    </div>
                    <div className="box-border flex flex-wrap  ">
                        <div className="box-border w-full max-w-full flex-shrink-0 ">
                        <ul className="my-0 box-border pl-0 ">
                            <li className="float-left mr-3.5 box-border last:mr-0 ">
                            <Link
                                className="float-left box-border text-center text-base font-normal text-white hover:block min-w-[200px] bg-yellow-400 rounded-[25px]"
                                target="_blank"
                                href="https://www.mycourseville.com/?q=onlinecourse/course/34730"
                            >
                                บุคคลทั่วไป
                            </Link>
                            </li>
                        </ul>
                        </div>
                    </div>
                    </div>
                </div>
                <div className="-mt-0 box-border w-full max-w-full flex-shrink-0 pl-5 md:w-5/6 lg:w-1/2 ">
                    {/* IMAGE */}
                    {/*<div className="img-width"><img src="images/course/courseIT-01.jpg"></div>*/}
                    {/* VDO */}
                    <div className="relative box-border w-full overflow-hidden">
                        <iframe width="546" height="307" src="https://www.youtube.com/embed/ukZNOXnKvs8" title="CHULA MOOC | การดูแลตนเองเพื่อการเป็นผู้สูงวัยสุขภาพดีมีความสุข"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"></iframe>
                    </div>
                </div>
                </div>
            </div>
            </div>
      </div> 
        
        <div className="box-border w-full max-w-full flex-shrink-0 flex flex-col items-center py-10">
            <div
                className="flex space-x-3 items-center px-1 py-1 bg-gradient-to-r from-blue-400 to-indigo-500 rounded-full drop-shadow-md w-fit">
                <div className="box-border flex justify-center items-center h-10 w-10 bg-white rounded-[50%]">
                    <FontAwesomeIcon icon={faCalendar} style={{width: '20px'}} className='text-blue-400 box-border inline-block not-italic leading-none' />
                </div>
                <span className="text-white text-xl pr-2 font-bold">ช่วงเวลาเรียนสำหรับบุคคลทั่วไป</span>
            </div>
        </div>
        <div className="relative box-border md:flex w-full max-w-full flex-shrink-0 pl-0 ">
        <div className="box-border z-[-1]">
        <img src="https://mooc.chula.ac.th/img/upload/การดูแลตนเองเพื่อการเป็นผู้สูงวัยสุขภาพ.png" />
        </div>
    <div className="bg-gray-100 pl-10 md:pl-20 pt-10 box-border tracking-normal w-[calc(100%_-_12px)]">
      <div className="box-border flex flex-wrap mt-[calc(-0px_*_-1)] mr-[calc(1.5rem_/_-2)] ml-[calc(1.5rem_/_-2)]">
        <div className="box-border w-full  max-w-full flex-shrink-0 text-lg leading-8 md:w-1/3 lg:w-1/3 pr-[calc(var(--bs-gutter-x)_/_2)] pl-[calc(var(--bs-gutter-x)_/_2)] mt-[var(--bs-gutter-y)] text-[rgba(37,37,37,1)]">
          เนื้อหา
        </div>
        <div className="box-border w-full max-w-full flex-shrink-0 pl-0 text-base leading-8 md:w-2/3 lg:w-2/3 pr-[calc(var(--bs-gutter-x)_/_2)] mt-[var(--bs-gutter-y)]">
          8 บทเรียน
        </div>
      </div>
      <div className="box-border flex flex-wrap mt-[calc(-0px_*_-1)] mr-[calc(1.5rem_/_-2)] ml-[calc(1.5rem_/_-2)]">
        <div className="box-border w-full max-w-full flex-shrink-0 text-lg leading-8 md:w-1/3 lg:w-1/3 pr-[calc(var(--bs-gutter-x)_/_2)] pl-[calc(var(--bs-gutter-x)_/_2)] mt-[var(--bs-gutter-y)]  text-[rgba(37,37,37,1)]">
          กลุ่มเป้าหมาย
        </div>
        <div className="box-border w-full max-w-full flex-shrink-0 pl-0 text-base leading-8 md:w-2/3 lg:w-2/3 pr-[calc(var(--bs-gutter-x)_/_2)] mt-[var(--bs-gutter-y)]">
          นักเรียน นิสิต นักศึกษา และบุคคลทั่วไป จำนวน 5,000 คน
        </div>
      </div>
      <div className="box-border flex flex-wrap mt-[calc(-0px_*_-1)] mr-[calc(1.5rem_/_-2)] ml-[calc(1.5rem_/_-2)]">
        <div className="box-border w-full max-w-full flex-shrink-0 text-lg leading-8 md:w-1/3 lg:w-1/3 pr-[calc(var(--bs-gutter-x)_/_2)] pl-[calc(var(--bs-gutter-x)_/_2)] mt-[var(--bs-gutter-y)]  text-[rgba(37,37,37,1)]">
          เกณฑ์การเรียนจบ
        </div>
        <div className="box-border w-full max-w-full flex-shrink-0 pl-0 text-base leading-8 md:w-2/3 lg:w-2/3 pr-[calc(var(--bs-gutter-x)_/_2)] mt-[var(--bs-gutter-y)]">
          ผู้เรียนต้องทำคะแนนรวมทั้งหมดให้ได้ร้อยละ 60 ขึ้นไป
        </div>
      </div>
      <div className="box-border flex flex-wrap mt-[calc(-0px_*_-1)] mr-[calc(1.5rem_/_-2)] ml-[calc(1.5rem_/_-2)]">
        <div className="box-border w-full max-w-full flex-shrink-0 text-lg  leading-8 md:w-1/3 lg:w-1/3 pr-[calc(var(--bs-gutter-x)_/_2)] pl-[calc(var(--bs-gutter-x)_/_2)] mt-[var(--bs-gutter-y)]  text-[rgba(37,37,37,1)]">
          แพลตฟอร์ม
        </div>
        <div className="box-border w-full max-w-full flex-shrink-0 pl-0 text-base leading-8 md:w-2/3 lg:w-2/3 pr-[calc(var(--bs-gutter-x)_/_2)] mt-[var(--bs-gutter-y)]">
          myCourseVille
        </div>
      </div>
    </div>
  </div>
  <div className='md:flex px-10 pt-10'>
    <span className="box-border w-1/2 p-5 space-y-3.5 > * + *">
        <div className="box-border w-full max-w-full flex-shrink-0 flex flex-col  pb-5">
            <div
                className="flex space-x-3 items-center px-1 py-1 bg-gradient-to-r from-blue-400 to-indigo-500 rounded-full drop-shadow-md w-fit">
                <div className="box-border flex justify-center items-center h-10 w-10 bg-white rounded-[50%]">
                    <FontAwesomeIcon icon={faBook} style={{width: '20px'}} className='text-blue-400 box-border inline-block not-italic leading-none' />
                </div>
                <span className="text-white text-xl pr-2 font-bold">เกี่ยวกับรายวิชา</span>
            </div>
        </div>  
        <p>
        วิชา การดูแลตนเองเพื่อการเป็นผู้สูงวัยสุขภาพดีมีความสุข (Aging Society and The Oral Health Care) เป็นการนำเสนอความรู้เรื่องการดูแลสุขภาพตนเองซึ่งเป็นเรื่องที่สำคัญ เพื่อให้ประชาชนมีสุขภาพดีและมีความสุขในทุกช่วงวัย โดยจะมุ่งเน้นการสร้างความรอบรู้ด้านสุขภาพในมิติต่าง ๆ ตามแนวทางการบูรณาการดูแลผู้สูงอายุขององค์การอนามัยโลก ซึ่งเป็นผลผลิตจากการประชุมผู้เชี่ยวชาญ และความร่วมมือกับกรมอนามัย กรมการแพทย์ สำนักอนามัย สสส. ภายใต้โครงการบูรณาการสหศาสตร์เพื่อรองรับสังคมสูงวัย (จุฬาอารี) เพื่อให้ผู้เรียนมีความรู้และทักษะที่จำเป็นก่อนเข้าสู่วัยผู้สูงอายุ สำหรับเนื้อหาวิชาจะประกอบด้วย ความรอบรู้ และการตระหนักรู้ตนเองด้านสุขภาพ กิจกรรมทางกาย โภชนาการเพื่อสุขภาพดี การได้ยิน และการมองเห็น การดูแลตนเองเพื่อชะลอสมองเสื่อม การดูแลสุขภาพช่องปาก และการดูแลสุขภาพจิต เป็นต้น
        </p>
    </span>

    <span className='w-1/2 p-5 space-y-3.5 > * + *'>
        <div className="box-border w-full max-w-full flex-shrink-0 flex flex-col pb-5">
            <div
                className="flex space-x-3 items-center px-1 py-1 bg-gradient-to-r from-blue-400 to-indigo-500 rounded-full drop-shadow-md w-fit">
                <div className="box-border flex justify-center items-center h-10 w-10 bg-white rounded-[50%]">
                    <FontAwesomeIcon icon={faPenToSquare} style={{width: '20px'}} className='text-blue-400 box-border inline-block not-italic leading-none' />
                </div>
                <span className="text-white text-xl pr-2 font-bold">เนื้อหารายวิชา</span>
            </div>
        </div>  
        <p>หัวข้อวิชา การดูแลตนเองเพื่อการเป็นผู้สูงวัยสุขภาพดีมีความสุข</p>
        <p>บทที่ 1 ความรอบรู้และการตระหนักรู้ตนเองด้านสุขภาพตามแนวทางองค์การอนามัยโลก</p>
        <p>บทที่ 2 กิจกรรมทางกายเพื่อสุขภาพดีมีความสุข</p>
        <p>บทที่ 3 โภชนาการเพื่อสุขภาพดีมีความสุข</p>
        <p>บทที่ 4 การได้ยินและการมองเห็นเพื่อสุขภาพดีมีความสุข</p>
        <p>บทที่ 5 การดูแลตนเองเพื่อชะลอสมองเสื่อมเพื่อสุขภาพดีมีความสุข</p>
        <p>บทที่ 6 การดูแลสุขภาพจิตเพื่อสุขภาพดีมีความสุขและสุขภาวะ</p>
    </span>

  </div>
  <div className='md:flex px-10 pt-10'>
    <span className="box-border w-1/2 p-5 space-y-3.5 > * + *">
        <div className="box-border w-full max-w-full flex-shrink-0 flex flex-col  pb-5">
            <div
                className="flex space-x-3 items-center px-1 py-1 bg-gradient-to-r from-blue-400 to-indigo-500 rounded-full drop-shadow-md w-fit">
                <div className="box-border flex justify-center items-center h-10 w-10 bg-white rounded-[50%]">
                    <FontAwesomeIcon icon={faFilePen} style={{width: '20px'}} className='text-blue-400 box-border inline-block not-italic leading-none' />
                </div>
                <span className="text-white text-xl pr-2 font-bold">เกณฑ์การวัดและประเมินผล</span>
            </div>
        </div>  
        <p>
        การวัดและประเมินผลผ่านแบบทดสอบย่อย (Quiz) และแบบทดสอบหลังเรียน (Posttest) โดยจะแบ่งเป็นคะแนนจาก Quiz เท่ากับ 50 คะแนน และคะแนนจาก Posttest เท่ากับ 50 คะแนน ทั้งนี้ผู้เรียนต้องทำคะแนนรวมทั้งหมดให้ได้ร้อยละ 60 ขึ้นไปจึงจะสามารถขอรับ Certificate of Completion ได้
        </p>
    </span>

    <span className='w-1/2 p-5 space-y-3.5 > * + *'>
        <div className="box-border w-full max-w-full flex-shrink-0 flex flex-col pb-5">
            <div
                className="flex space-x-3 items-center px-1 py-1 bg-gradient-to-r from-blue-400 to-indigo-500 rounded-full drop-shadow-md w-fit">
                <div className="box-border flex justify-center items-center h-10 w-10 bg-white rounded-[50%]">
                    <FontAwesomeIcon icon={faBullseye} style={{width: '20px'}} className='text-blue-400 box-border inline-block not-italic leading-none' />
                </div>
                <span className="text-white text-xl pr-2 font-bold">วัตถุประสงค์</span>
            </div>
        </div>  
        <p>1.เพื่อให้ผู้เรียนสามารถนำความรู้ที่ได้จากบทเรียนไปใช้ในการดูแลตนเองเพื่อเตรียมพร้อมสู่การเป็นผู้สูงวัยสุขภาพดีมีความสุข</p>
        <p>
        2.เพื่อให้ผู้เรียนสามารถถ่ายทอดความรู้และทักษะในการดูแลสุขภาพตนเองแก่ประชาชนทั่วไปและผู้ที่สนใจการดูแลตนเองสู่การเป็นผู้สูงวัยสุขภาพดีมีความสุข
        </p>
    </span>

  </div>
  <div className='md:flex px-10 pt-10'>
    <span className="box-border w-1/2 p-5 space-y-3.5 > * + *">
        <div className="box-border w-full max-w-full flex-shrink-0 flex flex-col  pb-5">
            <div
                className="flex space-x-3 items-center px-1 py-1 bg-gradient-to-r from-blue-400 to-indigo-500 rounded-full drop-shadow-md w-fit">
                <div className="box-border flex justify-center items-center h-10 w-10 bg-white rounded-[50%]">
                    <FontAwesomeIcon icon={faThumbtack} style={{width: '20px'}} className='text-blue-400 box-border inline-block not-italic leading-none' />
                </div>
                <span className="text-white text-xl pr-2 font-bold">หมายเหตุ</span>
            </div>
        </div>  
        <p>1. ผู้เรียนจะมีสิทธิ์ทำแบบทดสอบหลังเรียน (Posttest) เมื่อเข้าร่วมกิจกรรมการเรียน (Course Progress) มากกว่า 80% ขึ้นไป</p>
        <p>
        2. แบบทดสอบหลังเรียน (Posttest) ในแต่ละวิชาจะสามารถทำได้แค่ครั้งเดียวเท่านั้น
        </p>
    </span>

  </div>
  <div className="box-border w-full max-w-full flex-shrink-0 flex flex-col items-center py-10 mb-10">
        <div
            className="flex space-x-3 items-center px-1 py-1 bg-gradient-to-r from-blue-400 to-indigo-500 rounded-full drop-shadow-md w-fit mb-10">
            <div className="box-border flex justify-center items-center h-10 w-10 bg-white rounded-[50%]">
                <FontAwesomeIcon icon={faLaptop} style={{width: '20px'}} className='text-blue-400 box-border inline-block not-italic leading-none' />
            </div>
            <span className="text-white text-xl pr-2 font-bold">อาจารย์ผู้สอน
            </span>
        </div>
        <img className="box-border h-44 w-auto align-middle pb-5" src="https://mooc.chula.ac.th/img/upload/ผศ. ดร.ทรงศักดิ์ หมัดสะและ.png"></img>
        <span className="box-border text-base underline decoration-sky-500 underline-offset-8 pb-5">
        ผศ. ดร.ทรงศักดิ์ หมัดสะ
        </span>
        <p className='text-sm'>ภาควิชาภาษาตะวันออก คณะนิติศาสตร์</p>
        <p className='text-sm'>มหาวิทยาลัยขอนแก่น</p>
    </div>
    <center className="box-border bg-gradient-to-r from-cyan-100 to-blue-100">
        <div className="relative box-border md:h-64 h-48 ">
          <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 ">
              <p className="my-0 box-border whitespace-nowrap text-4xl text-[rgba(112,112,112,1)] tracking-[3.2px]">
                  คอร์สแนะนำ
              </p>
              </div>
          </div>
        <hr className="my-6 box-content h-0 overflow-visible border-solid" />
      </center>
    
    <Carousel />
      
      <div className="relative box-border w-full max-w-full flex flex-col items-center top-[-90px]">
        <div className="box-border ">
          <Link
            className="box-border rounded-3xl text-center font-medium normal-case tracking-normal border border-[rgba(200,0,114,1)] text-[rgba(200,0,114,1)] open:cursor-pointer font-[inherit] leading-[inherit] min-w-[140px] py-2 px-6 text-sm"
            href="/courses"
          >
         <FontAwesomeIcon icon={faArrowLeft} style={{width: '10px'}} className='text-[rgba(200,0,114,1)] box-border inline-block not-italic leading-none' />
         &nbsp;&nbsp;ย้อนกลับ
          </Link>
        </div>
      </div>
  <Footer />
      </>   
    );
}

export default Detail