import Footer from 'components/Footer';
import Header from 'components/Header';
import Head from "next/head";
import Link from "next/link";
import Script from 'next/script'

const Detail = () => {
    return (
        <>
        <Head>
            <title>Lawlibrarykku</title>
            <meta name="description" content="Generated by create-LawKKU-app" />
            <link rel="icon" href="/favicon.ico" />
            <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css" rel="stylesheet" />
        </Head>
        <Header />
        <div className="relative box-border ">
            <div className="w-full box-border bg-gradient-to-r from-cyan-100 to-blue-100 p-10 ">
            <div className="box-border ">
                <div className="box-border flex flex-wrap justify-center ">
                <div className="box-border w-full max-w-full flex-shrink-0 pr-5 md:w-5/6 lg:w-1/2 ">
                    <div className="box-border ">
                    <div className="box-border flex flex-wrap ">
                        <div className="box-border w-full max-w-full flex-shrink-0 ">
                        <h4 className="mt-0 mb-2 box-border text-2xl font-medium tracking-wide xl:text-2xl leading-[normal]  text-[rgba(17,17,17,1)]">
                            การดูแลตนเองเพื่อการเป็นผู้สูงวัยสุขภาพดีมีความสุข
                        </h4>
                        </div>
                    </div>
                    <div className="box-border flex flex-wrap ">
                        <div className="box-border w-full max-w-full flex-shrink-0 ">
                        <ul className="float-left mt-0 mb-6 box-border w-full pl-0 ">
                            <li className="float-left mb-0.5 box-border w-full text-base font-normal leading-7 tracking-normal text-[rgba(54,54,54,1)]">
                            <strong className="float-left box-border pr-3 font-semibold text-[rgba(37,37,37,1)]">
                                โดย :{" "}
                            </strong>
                            ทีมคณาจารย์จาก CHULA ARi
                            </li>
                            <li className="float-left mb-0.5 box-border w-full text-base font-normal leading-7 tracking-normal text-[rgba(54,54,54,1)]">
                            <strong className="float-left box-border pr-3 font-semibold text-[rgba(37,37,37,1)]">
                                รหัส :{" "}
                            </strong>
                            MOOC5021
                            </li>
                            <li className="float-left mb-0.5 box-border w-full text-base font-normal leading-7 tracking-normal text-[rgba(54,54,54,1)]">
                            <strong className="float-left box-border pr-3.5 font-semibold text-[rgba(37,37,37,1)]">
                                หมู่ :{" "}
                            </strong>
                            <div className="float-left mt-0.5 box-border rounded-2xl text-center text-xs font-medium leading-4 tracking-wide min-w-[55px] bg-[rgba(244,149,34,1)] text-white border-[rgba(244,149,34,1)]">
                                กฏหมาย
                            </div>
                            </li>
                        </ul>
                        </div>
                    </div>
                    <div className="box-border flex flex-wrap ">
                        <div className="box-border w-full max-w-full flex-shrink-0 pr-[calc(var(--bs-gutter-x)_/_2)] pl-[calc(var(--bs-gutter-x)_/_2)] mt-[var(--bs-gutter-y)]"></div>
                    </div>
                    <div className="box-border flex flex-wrap ">
                        <div className="box-border w-full max-w-full flex-shrink-0 ">
                        <h6 className="mt-0 mb-5 box-border text-lg font-semibold tracking-normal leading-[normal] font-[Sarabun,_sans-serif] text-[rgba(17,17,17,1)]">
                            ลงทะเบียนเรียน
                        </h6>
                        </div>
                    </div>
                    <div className="box-border flex flex-wrap  ">
                        <div className="box-border w-full max-w-full flex-shrink-0 ">
                        <ul className="my-0 box-border pl-0 ">
                            <li className="float-left mr-3.5 box-border last:mr-0 ">
                            <Link
                                className="float-left box-border text-center text-base font-normal text-white hover:block min-w-[200px] bg-yellow-400 rounded-[25px]"
                                target="_blank"
                                href="https://www.mycourseville.com/?q=onlinecourse/course/34730"
                            >
                                บุคคลทั่วไป
                            </Link>
                            </li>
                        </ul>
                        </div>
                    </div>
                    </div>
                </div>
                <div className="-mt-0 box-border w-full max-w-full flex-shrink-0 pl-5 md:w-5/6 lg:w-1/2 ">
                    {/* IMAGE */}
                    {/*<div className="img-width"><img src="images/course/courseIT-01.jpg"></div>*/}
                    {/* VDO */}
                    <div className="relative box-border w-full overflow-hidden">
                        <iframe width="546" height="307" src="https://www.youtube.com/embed/ukZNOXnKvs8" title="CHULA MOOC | การดูแลตนเองเพื่อการเป็นผู้สูงวัยสุขภาพดีมีความสุข"  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"></iframe>
                    </div>
                </div>
                </div>
            </div>
            </div>
      </div> 
        
        <div className="box-border w-full max-w-full flex-shrink-0 flex flex-col items-center py-10">
            <div
                className="flex space-x-3 items-center px-1 py-1 bg-indigo-500 rounded-full drop-shadow-md w-fit">
                <div className="box-border flex justify-center items-center h-10 w-10 bg-white rounded-[50%]">
                    <img className="box-border h-6 w-6 " src="https://mooc.chula.ac.th/images/icon/icon-calendar.svg" />
                </div>
                <span className="text-white text-xl pr-2 font-bold">ช่วงเวลาเรียนสำหรับบุคคลทั่วไป</span>
            </div>
        </div>
        <div className="relative box-border md:flex w-full max-w-full flex-shrink-0 pl-0 ">
        <div className="box-border z-[-1]">
        <img src="https://mooc.chula.ac.th/img/upload/การดูแลตนเองเพื่อการเป็นผู้สูงวัยสุขภาพ.png" />
        </div>
    <div className="bg-gray-100 pl-10 md:pl-20 pt-10 box-border tracking-normal w-[calc(100%_-_12px)]">
      <div className="box-border flex flex-wrap mt-[calc(-0px_*_-1)] mr-[calc(1.5rem_/_-2)] ml-[calc(1.5rem_/_-2)]">
        <div className="box-border w-full  max-w-full flex-shrink-0 text-lg leading-8 md:w-1/3 lg:w-1/3 pr-[calc(var(--bs-gutter-x)_/_2)] pl-[calc(var(--bs-gutter-x)_/_2)] mt-[var(--bs-gutter-y)] text-[rgba(37,37,37,1)]">
          เนื้อหา
        </div>
        <div className="box-border w-full max-w-full flex-shrink-0 pl-0 text-base leading-8 md:w-2/3 lg:w-2/3 pr-[calc(var(--bs-gutter-x)_/_2)] mt-[var(--bs-gutter-y)]">
          8 บทเรียน
        </div>
      </div>
      <div className="box-border flex flex-wrap mt-[calc(-0px_*_-1)] mr-[calc(1.5rem_/_-2)] ml-[calc(1.5rem_/_-2)]">
        <div className="box-border w-full max-w-full flex-shrink-0 text-lg leading-8 md:w-1/3 lg:w-1/3 pr-[calc(var(--bs-gutter-x)_/_2)] pl-[calc(var(--bs-gutter-x)_/_2)] mt-[var(--bs-gutter-y)]  text-[rgba(37,37,37,1)]">
          กลุ่มเป้าหมาย
        </div>
        <div className="box-border w-full max-w-full flex-shrink-0 pl-0 text-base leading-8 md:w-2/3 lg:w-2/3 pr-[calc(var(--bs-gutter-x)_/_2)] mt-[var(--bs-gutter-y)]">
          นักเรียน นิสิต นักศึกษา และบุคคลทั่วไป จำนวน 5,000 คน
        </div>
      </div>
      <div className="box-border flex flex-wrap mt-[calc(-0px_*_-1)] mr-[calc(1.5rem_/_-2)] ml-[calc(1.5rem_/_-2)]">
        <div className="box-border w-full max-w-full flex-shrink-0 text-lg leading-8 md:w-1/3 lg:w-1/3 pr-[calc(var(--bs-gutter-x)_/_2)] pl-[calc(var(--bs-gutter-x)_/_2)] mt-[var(--bs-gutter-y)]  text-[rgba(37,37,37,1)]">
          เกณฑ์การเรียนจบ
        </div>
        <div className="box-border w-full max-w-full flex-shrink-0 pl-0 text-base leading-8 md:w-2/3 lg:w-2/3 pr-[calc(var(--bs-gutter-x)_/_2)] mt-[var(--bs-gutter-y)]">
          ผู้เรียนต้องทำคะแนนรวมทั้งหมดให้ได้ร้อยละ 60 ขึ้นไป
        </div>
      </div>
      <div className="box-border flex flex-wrap mt-[calc(-0px_*_-1)] mr-[calc(1.5rem_/_-2)] ml-[calc(1.5rem_/_-2)]">
        <div className="box-border w-full max-w-full flex-shrink-0 text-lg  leading-8 md:w-1/3 lg:w-1/3 pr-[calc(var(--bs-gutter-x)_/_2)] pl-[calc(var(--bs-gutter-x)_/_2)] mt-[var(--bs-gutter-y)]  text-[rgba(37,37,37,1)]">
          แพลตฟอร์ม
        </div>
        <div className="box-border w-full max-w-full flex-shrink-0 pl-0 text-base leading-8 md:w-2/3 lg:w-2/3 pr-[calc(var(--bs-gutter-x)_/_2)] mt-[var(--bs-gutter-y)]">
          myCourseVille
        </div>
      </div>
    </div>
  </div>
  <div className='md:flex p-10'>
  <span className="box-border w-1/2 p-5">
    <p className="mt-0 mb-11  box-border table text-3xl font-medium tracking-wide xl:text-3xl leading-[normal]  text-[rgba(17,17,17,1)] underline decoration-sky-500 underline-offset-8">
    เกี่ยวกับรายวิชา
          </p>
    <p>
    วิชา การดูแลตนเองเพื่อการเป็นผู้สูงวัยสุขภาพดีมีความสุข (Aging Society and The Oral Health Care) เป็นการนำเสนอความรู้เรื่องการดูแลสุขภาพตนเองซึ่งเป็นเรื่องที่สำคัญ เพื่อให้ประชาชนมีสุขภาพดีและมีความสุขในทุกช่วงวัย โดยจะมุ่งเน้นการสร้างความรอบรู้ด้านสุขภาพในมิติต่าง ๆ ตามแนวทางการบูรณาการดูแลผู้สูงอายุขององค์การอนามัยโลก ซึ่งเป็นผลผลิตจากการประชุมผู้เชี่ยวชาญ และความร่วมมือกับกรมอนามัย กรมการแพทย์ สำนักอนามัย สสส. ภายใต้โครงการบูรณาการสหศาสตร์เพื่อรองรับสังคมสูงวัย (จุฬาอารี) เพื่อให้ผู้เรียนมีความรู้และทักษะที่จำเป็นก่อนเข้าสู่วัยผู้สูงอายุ สำหรับเนื้อหาวิชาจะประกอบด้วย ความรอบรู้ และการตระหนักรู้ตนเองด้านสุขภาพ กิจกรรมทางกาย โภชนาการเพื่อสุขภาพดี การได้ยิน และการมองเห็น การดูแลตนเองเพื่อชะลอสมองเสื่อม การดูแลสุขภาพช่องปาก และการดูแลสุขภาพจิต เป็นต้น
    </p>
    <br />
    <p>หัวข้อวิชา การดูแลตนเองเพื่อการเป็นผู้สูงวัยสุขภาพดีมีความสุข</p>
    <br />
    <p>บทที่ 1 ความรอบรู้และการตระหนักรู้ตนเองด้านสุขภาพตามแนวทางองค์การอนามัยโลก</p>
    <p>บทที่ 2 กิจกรรมทางกายเพื่อสุขภาพดีมีความสุข</p>
    <p>บทที่ 3 โภชนาการเพื่อสุขภาพดีมีความสุข</p>
    <p>บทที่ 4 การได้ยินและการมองเห็นเพื่อสุขภาพดีมีความสุข</p>
    <p>บทที่ 5 การดูแลตนเองเพื่อชะลอสมองเสื่อมเพื่อสุขภาพดีมีความสุข

</p>
    <p>บทที่ 6 การดูแลสุขภาพจิตเพื่อสุขภาพดีมีความสุขและสุขภาวะ

</p>
</span>

  <span className='w-1/2 p-5'>
  <p className="mt-0 mb-11  box-border table text-3xl font-medium tracking-wide xl:text-3xl leading-[normal]  text-[rgba(17,17,17,1)] underline decoration-sky-500 underline-offset-8">
  วัตถุประสงค์
          </p>
    <p>1.เพื่อให้ผู้เรียนสามารถนำความรู้ที่ได้จากบทเรียนไปใช้ในการดูแลตนเองเพื่อเตรียมพร้อมสู่การเป็นผู้สูงวัยสุขภาพดีมีความสุข</p>
    <p>
    2.เพื่อให้ผู้เรียนสามารถถ่ายทอดความรู้และทักษะในการดูแลสุขภาพตนเองแก่ประชาชนทั่วไปและผู้ที่สนใจการดูแลตนเองสู่การเป็นผู้สูงวัยสุขภาพดีมีความสุข
    </p>

  </span>

  </div>
  <Footer />
      </>   
    );
}

export default Detail