import Footer from "components/Footer";
import Header from "components/Header";
import Slider from "components/Slider";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Lawlibrarykku</title>
        <meta name="description" content="Generated by create-LawKKU-app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css" rel="stylesheet" />
      </Head>
      <Header />
      <Slider />
      <center className="box-border bg-gradient-to-r from-cyan-100 to-blue-100">
        <div className="relative box-border h-64 ">
          <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 ">
              <p className="my-0 box-border whitespace-nowrap text-4xl text-[rgba(112,112,112,1)] tracking-[3.2px]">
                  คอร์สใหม่
              </p>
              </div>
          </div>
        <hr className="my-6 box-content h-0 overflow-visible border-solid" />
      </center>
      <div className="relative box-border justify-center lg:columns-3 columns-1 md:columns-2 space-y-3 px-10 top-[-120px]">
        <div className="max-w-sm rounded overflow-hidden shadow-lg">
            <img className="w-full" src="https://lawlibrarykku.online/getclassimg/_LW013215_พระธรรมนูญศาลยุติธรรม" alt="Sunset in the mountains" />
            <div className="px-6 py-4">
                <div className="font-bold text-base mb-2">พระธรรมนูญศาลยุติธรรม</div>
                <div className="box-border flex flex-row">
                    <p className="text-gray-700 text-base">
                    LW013215
                    </p>
                    <div className="box-border w-full max-w-full flex-shrink-0 pl-0 lg:w-1/3 ">
                        <div className="float-right box-border rounded-sm text-center text-xs font-medium bg-[#4d40f7] text-[#ffee00] p-0.5">
                            956 ที่ว่าง
                        </div>
                    </div>
                </div>
            </div>
            <div className="px-6 pt-4 pb-2">
                <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#พระธรรมนูญ</span>
            </div>
        </div>
        <div className="max-w-sm rounded overflow-hidden shadow-lg">
            <img className="w-full" src="https://lawlibrarykku.online/getclassimg/_LW014112_การระงับและการไกล่เกลี่ยข้อพิพาท" alt="Sunset in the mountains" />
            <div className="px-6 py-4">
                <div className="font-bold text-base mb-2">การระงับและการไกล่เกลี่ยข้อพิพาท</div>
                <div className="box-border flex flex-row">
                    <p className="text-gray-700 text-base">
                    LW014112
                    </p>
                    <div className="box-border w-full max-w-full flex-shrink-0 pl-0 lg:w-1/3 ">
                        <div className="float-right box-border rounded-sm text-center text-xs font-medium bg-[#4d40f7] text-[#ffee00] p-0.5">
                            999 ที่ว่าง
                        </div>
                    </div>
                </div>
            </div>
            <div className="px-6 pt-4 pb-2">
                <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#ข้อพิพาท</span>
                <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#ไกล่เกลี่ย</span>
            </div>
        </div>
        <div className="max-w-sm rounded overflow-hidden shadow-lg">
            <img className="w-full" src="https://lawlibrarykku.online/getclassimg/___LW012501 กฎหมายอาญา : บทบัญญัติทั่วไป" alt="Sunset in the mountains" />
            <div className="px-6 py-4">
                <div className="font-bold text-base mb-2">กฎหมายอาญา : บทบัญญัติทั่วไป</div>
                <div className="box-border flex flex-row">
                    <p className="text-gray-700 text-base">
                    LW012501
                    </p>
                    <div className="box-border w-full max-w-full flex-shrink-0 pl-0 lg:w-1/3 ">
                      <div className="float-right box-border rounded-sm text-center text-xs font-medium bg-[#4d40f7] text-[#ffee00] p-0.5">
                            999 ที่ว่าง
                        </div>
                    </div>
                </div>
            </div>
            <div className="px-6 pt-4 pb-2">
                <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#กฎหมาย</span>
                <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#กฎหมายอาญา</span>
            </div>
        </div>
    </div>
      <div className="relative box-border w-full max-w-full flex flex-col items-center top-[-90px]">
        <div className="box-border ">
          <Link
            className="box-border rounded-3xl text-center font-medium normal-case tracking-normal border border-[rgba(200,0,114,1)] text-[rgba(200,0,114,1)] open:cursor-pointer font-[inherit] leading-[inherit] min-w-[140px] py-2 px-6 text-sm"
            href="/courses"
          >
            ดูทั้งหมด
          </Link>
        </div>
      </div>
      <div className="flow-root">
          <h2 className="mt-0 mb-11 float-left box-border table text-3xl font-medium tracking-wide xl:text-3xl leading-[normal]  text-[rgba(17,17,17,1)] underline decoration-sky-500 underline-offset-8 pl-10">
          คอร์สที่กำลังเปิด
          </h2>
          <div className="box-border pt-3 float-right pr-10">
          <Link className="box-border rounded-3xl text-center font-medium normal-case tracking-normal border border-[rgba(200,0,114,1)] text-[rgba(200,0,114,1)] open:cursor-pointer font-[inherit] leading-[inherit] w-[140px] py-2 px-6 text-sm" href="/courses">ดูทั้งหมด</Link>
        </div>
      </div>
      <div className="box-border justify-center lg:columns-3 columns-1 md:columns-2 space-y-3 px-10 pb-10">
          <div className="max-w-sm rounded overflow-hidden shadow-lg">
              <img className="w-full" src="https://lawlibrarykku.online/getclassimg/LW011101_กฎหมายกับสังคม" alt="Sunset in the mountains" />
              <div className="px-6 py-4">
                  <div className="font-bold text-base mb-2">กฎหมายกับสังคม</div>
                  <div className="box-border flex flex-row">
                      <p className="text-gray-700 text-base">
                      LW011101
                      </p>
                      <div className="box-border w-full max-w-full flex-shrink-0 pl-0 lg:w-1/3 ">
                          <div className="float-right box-border rounded-sm text-center text-xs font-medium bg-[#4d40f7] text-[#ffee00] p-0.5">
                              66 ที่ว่าง
                          </div>
                      </div>
                  </div>
              </div>
              <div className="px-6 pt-4 pb-2">
                  <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#กฎหมาย</span>
                  <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#สังคม</span>
              </div>
          </div>
          <div className="max-w-sm rounded overflow-hidden shadow-lg">
              <img className="w-full" src="https://lawlibrarykku.online/getclassimg/LW011201_หลักกฎหมายเอกชน" alt="Sunset in the mountains" />
              <div className="px-6 py-4">
                  <div className="font-bold text-base mb-2">หลักกฎหมายเอกชน</div>
                  <div className="box-border flex flex-row">
                      <p className="text-gray-700 text-base">
                      LW011201
                      </p>
                      <div className="box-border w-full max-w-full flex-shrink-0 pl-0 lg:w-1/3 ">
                          <div className="float-right box-border rounded-sm text-center text-xs font-medium bg-[#4d40f7] text-[#ffee00] p-0.5">
                              172 ที่ว่าง
                          </div>
                      </div>
                  </div>
              </div>
              <div className="px-6 pt-4 pb-2">
                  <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#กฎหมาย</span>
                  <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#เอกชน</span>
              </div>
          </div>
          <div className="max-w-sm rounded overflow-hidden shadow-lg">
              <img className="w-full" src="https://lawlibrarykku.online/getclassimg/LW012102_นิติปรัชญา" alt="Sunset in the mountains" />
              <div className="px-6 py-4">
                  <div className="font-bold text-base mb-2">นิติปรัชญา</div>
                  <div className="box-border flex flex-row">
                      <p className="text-gray-700 text-base">
                      LW012102
                      </p>
                      <div className="box-border w-full max-w-full flex-shrink-0 pl-0 lg:w-1/3 ">
                          <div className="float-right box-border rounded-sm text-center text-xs font-medium bg-[#f03b3b] text-white p-0.5">
                              คอร์สเต็ม
                          </div>
                      </div>
                  </div>
              </div>
              <div className="px-6 pt-4 pb-2">
                  <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#นิติกรรม</span>
              </div>
          </div>
      </div>
      <main className="hidden flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
        </div>
      </main>
      <Footer />
      <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>
    </>
  );
};

export default Home;
