import React, { ReactNode } from "react";
import Footer from "~/layouts/Footer";
import Navbar from "~/layouts/Navbar";
import GotoTop from "./ui/GotoTop";

interface LayoutProps {
  children: ReactNode;
}

// export const metadata = {
//   title: "Lawlibrarykku",
//   description: "Generated by create-LawKKU-app",
// };

export default function Layout({ children }: LayoutProps): JSX.Element {
  return (
    <>
      <Navbar />
      <main>{children}</main>
      <Footer />
      <GotoTop />
    </>
  );
}
